### ISSUE TITLE
希望可以自定义本机ip

### ISSUE THREAD

**Issue by kzw200015** [arloor/nftables-nat-rust#13]
尽管现在可以自动探测本机ip，但是在多网卡的机器上就不方便使用了，比如两台通过iplc内网连接的机器，希望能加一个命令行参数手动指定

**Comment by arloor** [comment]
我在python版本上改下可以吗？



---原始邮件---
发件人: "yooomu"<notifications@github.com&gt;
发送时间: 2020年12月3日(周四) 晚上8:14
收件人: "arloor/nftables-nat-rust"<nftables-nat-rust@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [arloor/nftables-nat-rust] 希望可以自定义本机ip (#13)




 
尽管现在可以自动探测本机ip，但是在多网卡的机器上就不方便使用了，比如两台通过iplc内网连接的机器，希望能加一个命令行参数手动指定

**Comment by kzw200015** [comment]
@arloor 可以的，感谢

**Comment by Palpitace** [comment]
同求非常感谢

**Comment by arloor** [comment]
已支持自定义本机ip
