### ISSUE TITLE
请问如何转发到本地的其他端口上

### ISSUE THREAD

**Issue by Antairez** [arloor/nftables-nat-rust#18]
SINGLE,49999,59999,127.0.0.1

请问下是不是如上这个写法，目前测试下来无效，不清楚是不是还需要其他操作

**Comment by arloor** [comment]
不支持转发到本机的，有转发到本机的需求可以看下iptables，自己做下哈
PS：你网名很像redis作者

**Comment by Antairez** [comment]
> 不支持转发到本机的，有转发到本机的需求可以看下iptables，自己做下哈
> PS：你网名很像redis作者

感谢回复，已有iptables规则
iptables -A PREROUTING -t nat -p tcp --dport 443 -j REDIRECT --to-port 8443
iptables -t nat -A OUTPUT -o lo -p tcp --dport 443 -j REDIRECT --to-port 8443

但在启用nft的机器上无法使用
会提示
iptables v1.8.2 (nf_tables): table `nat' is incompatible, use 'nft' tool.

似乎现在只能二选一？

**Comment by arloor** [comment]
就我所之，nftables和iptables是兼容的，这个我也没遇到过

----------




--------------原始邮件--------------
发件人："Antairez ***@***.***&gt;;
发送时间：2022年10月14日(星期五) 晚上6:08
收件人："arloor/nftables-nat-rust" ***@***.***&gt;;
抄送："刘港欢 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [arloor/nftables-nat-rust] 请问如何转发到本地的其他端口上 (Issue #18)
-----------------------------------

 

  
不支持转发到本机的，有转发到本机的需求可以看下iptables，自己做下哈
 PS：你网名很像redis作者
  
感谢回复，已有iptables规则
 iptables -A PREROUTING -t nat -p tcp --dport 443 -j REDIRECT --to-port 8443
 iptables -t nat -A OUTPUT -o lo -p tcp --dport 443 -j REDIRECT --to-port 8443
 
但在启用nft的机器上无法使用
 会提示
 iptables v1.8.2 (nf_tables): table `nat' is incompatible, use 'nft' tool.
 
似乎现在只能二选一？

**Comment by arloor** [comment]
今天更新了下，支持了转发到本机其他端口哈
详见readme
