### ISSUE TITLE
过几天试下效果

### ISSUE THREAD

**Issue by jiayouzl** [arloor/nftables-nat-rust#2]
看了下源码,很合理,过些天试下.

**Comment by arloor** [comment]
确实是挺简单的功能，刚好用简单的代码实现，顺便用下rust，学习学习



---原始邮件---
发件人: "张雷"<notifications@github.com>
发送时间: 2020年3月2日(周一) 凌晨0:43
收件人: "arloor/nftables-nat-rust"<nftables-nat-rust@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [arloor/nftables-nat-rust] 过几天试下效果 (#2)



看了下源码,很合理,过些天试下.
