### ISSUE TITLE
可以增加本地ip的选项吗

### ISSUE THREAD

**Issue by kelemirxcv** [arloor/nftables-nat-rust#23]
你好，如果机器有多网卡，可以修改成 输入规则时增加本地ip的填写吗？

**Comment by arloor** [comment]
<img width="569" alt="image" src="https://github.com/arloor/nftables-nat-rust/assets/21768987/dee8132c-a68a-4495-82da-81336a85e60a">
readme里有写哈

**Comment by kelemirxcv** [comment]
意思是不同ip的转发需要每次echo一次本地ip再增加规则吗？

**Comment by arloor** [comment]
echo "nat_local_ip=10.10.10.10" > /opt/nat/env 只需要执行一次
