### ISSUE TITLE
trojan端口是443要怎么配置规则?谢谢~

### ISSUE THREAD

**Issue by jiayouzl** [arloor/nftables-nat-rust#3]
ssr转发正常,trojan是443端口没成功,nft add rule inet filter TCP tcp dport 443 accept我还自己添加了规则也不行.

**Comment by arloor** [comment]
应该都一样，我也不知道



---原始邮件---
发件人: "张雷"<notifications@github.com>
发送时间: 2020年3月2日(周一) 晚上11:03
收件人: "arloor/nftables-nat-rust"<nftables-nat-rust@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [arloor/nftables-nat-rust] trojan端口是443要怎么配置规则?谢谢~ (#3)



ssr转发正常,trojan是443端口没成功,nft add rule inet filter TCP tcp dport 443 accept我还自己添加了规则也不行.

**Comment by jiayouzl** [comment]
> 应该都一样，我也不知道
> […](#)

又试了下，torjan443端口不行，ssr这样自定义端口很完美。

**Comment by arloor** [comment]
我不觉得是nat的问题，你可以看看trojan对这种nat转发有没有什么限制
我能想到的限制之一是，要domain域名配置对(仅供参考



---原始邮件---
发件人: "张雷"<notifications@github.com>
发送时间: 2020年3月3日(周二) 凌晨2:36
收件人: "arloor/nftables-nat-rust"<nftables-nat-rust@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"liuganghuan"<admin@arloor.com>;
主题: Re: [arloor/nftables-nat-rust] trojan端口是443要怎么配置规则?谢谢~ (#3)


 
应该都一样，我也不知道
 …
  
又试了下，torjan443端口不行，ssr这样自定义端口很完美。
