### ISSUE TITLE
nat dns缓存问题，希望可以增加其他的域名解析ip方式

### ISSUE THREAD

**Issue by Garfield** [arloor/nftables-nat-rust#4]
nat dns缓存问题，希望可以增加其他的域名解析ip方式，通过dig查询dns解析域名ip存在缓存问题，能不能通过其他的方式解析ip，因为转发机很多都是nat收到母鸡影响,dns缓存又不会自动清理

**Comment by arloor** [comment]
比较难，因为需要跳过vps的系统直接查dns服务器，比如8888。如果自己造轮子，需要udp实现dns协议。
有时间的话，我看看有没有现成的轮子
没轮子肯定不做，有轮子的话有时间就做



---原始邮件---
发件人: "DarAee"<notifications@github.com>
发送时间: 2020年3月9日(周一) 下午5:05
收件人: "arloor/nftables-nat-rust"<nftables-nat-rust@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [arloor/nftables-nat-rust] nat dns缓存问题，希望可以增加其他的域名解析ip方式 (#4)



nat dns缓存问题，希望可以增加其他的域名解析ip方式，通过dig查询dns解析域名ip存在缓存问题，能不能通过其他的方式解析ip，因为转发机很多都是nat收到母鸡影响,dns缓存又不会自动清理

**Comment by Garfield** [comment]
不是，可能我表达的不太清楚，例如我有一台hkt nat ,ip老是变动，我通过一台山东中转机中转，用了您的nftables脚本，因为hkt域名是动态ddns的，被墙自动换，问题就在于我用山东中转机的时候，山东中转机也是nat,母鸡设置了dns缓存时间，需要3600s或者更长，就导致了目标ip已经发生了变化的情况下，本地通过dig查询dns是查询的到的缓存中的Ip,就导致了中转机不能及时的更新ip,出现了问题。
因为网上有很多通过域名解析成Ip的接口，可以直接从接口获取ip来判断域名ip是否发生变化，因为这个不会被母鸡的dns缓存影响



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liuganghuan"<notifications@github.com&gt;; 
发送时间: 2020年3月9日(星期一) 下午5:28
收件人: "arloor/nftables-nat-rust"<nftables-nat-rust@noreply.github.com&gt;; 
抄送: "Antake"<2284128416@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [arloor/nftables-nat-rust] nat dns缓存问题，希望可以增加其他的域名解析ip方式 (#4)



比较难，因为需要跳过vps的系统直接查dns服务器，比如8888。如果自己造轮子，需要udp实现dns协议。 
 有时间的话，我看看有没有现成的轮子 
 没轮子肯定不做，有轮子的话有时间就做 
 
 
 
 ---原始邮件--- 
 发件人: "DarAee"<notifications@github.com&gt; 
 发送时间: 2020年3月9日(周一) 下午5:05 
 收件人: "arloor/nftables-nat-rust"<nftables-nat-rust@noreply.github.com&gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
 主题: [arloor/nftables-nat-rust] nat dns缓存问题，希望可以增加其他的域名解析ip方式 (#4) 
 
 
 
 nat dns缓存问题，希望可以增加其他的域名解析ip方式，通过dig查询dns解析域名ip存在缓存问题，能不能通过其他的方式解析ip，因为转发机很多都是nat收到母鸡影响,dns缓存又不会自动清理
