### ISSUE TITLE
`flush table ip nat` 替代 `flush ruleset`

### ISSUE THREAD

**Issue by epizza** [arloor/nftables-nat-rust#5]
`/etc/nftables/nat-diy.nft` 的 `flush ruleset` 会清空全部 nftables 规则，是否考虑把 `flush ruleset` 替换成 `flush table ip nat`，这样清空 nftables 的规则仅限于 `nftables-nat-rust` 生成的，不会影响其他规则，同时无论 `/etc/nftables/nat-diy.nft` 是否已经载入转发规则都可以正常加载。

```
#!/usr/sbin/nft -f

add table ip nat
flush table ip nat

add table ip nat
add chain nat PREROUTING { type nat hook prerouting priority -100 ; }
add chain nat POSTROUTING { type nat hook postrouting priority 100 ; }
```

**Comment by arloor** [comment]
感谢建议和merge request
