### ISSUE TITLE
请求：提供 IPv6 支持

### ISSUE THREAD

**Issue by hsupu** [arloor/nftables-nat-rust#7]
如题，现有的设计只能产生 IPv4 的 TCP/UDP 的转发脚本，而 nftables 本身也支持 IPv6 间的转发，可否增加脚本对这方面的解析和支持呢？

**Comment by arloor** [comment]
不可



---原始邮件---
发件人: "Hsu Pu"<notifications@github.com&gt;
发送时间: 2020年6月4日(周四) 中午11:44
收件人: "arloor/nftables-nat-rust"<nftables-nat-rust@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [arloor/nftables-nat-rust] 请求：提供 IPv6 支持 (#7)




 
如题，现有的设计只能产生 IPv4 的 TCP/UDP 的转发脚本，而 nftables 本身也支持 IPv6 间的转发，可否增加脚本对这方面的解析和支持呢？
