### ISSUE TITLE
以后会支持负载均衡吗

### ISSUE THREAD

**Issue by qqppwskj** [arloor/nftables-nat-rust#8]
以后会支持负载均衡吗

**Comment by arloor** [comment]
不支持



---原始邮件---
发件人: "qqppwskj"<notifications@github.com&gt;
发送时间: 2020年7月9日(周四) 上午9:49
收件人: "arloor/nftables-nat-rust"<nftables-nat-rust@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [arloor/nftables-nat-rust] 以后会支持负载均衡吗 (#8)




 
以后会支持负载均衡吗
