### ISSUE TITLE
记一下Ubuntu20上踩过的坑，供参考

### ISSUE THREAD

**Issue by xianren78** [arloor/nftables-nat-rust#9]
lsmod | grep '^nf'
运行这个命令看看你的内核有没有nftables支持，nft_nat 模块等必须有。如果没有，先换内核再进行其他步骤
没有内核支持，运行/usr/local/bin/nat /etc/nat.conf能看到 Error: Could not process rule: Operation not supported错误

**Comment by arloor** [comment]
请问有问题的内核版本是什么啊？
换到什么内核版本能解决问题？

**Comment by xianren78** [comment]
> 请问有问题的内核版本是什么啊？
> 换到什么内核版本能解决问题？

一个NAT上自带的内核竟然没有nf_nat模块，坑死了
